name       : rkcommon
version    : 1.8.0
release    : 3
source     :
    - https://github.com/ospray/rkcommon/archive/refs/tags/v1.8.0.tar.gz : f037c15f7049610ef8bca37500b2ab00775af60ebbb9d491ba5fc2e5c04a7794
homepage   : https://github.com/ospray/rkcommon/
license    : Apache-2.0
component  : programming.library
summary    : Intel RenderKit common C++/CMake infrastructure
description: |
    This project represents a common set of C++ infrastructure and CMake utilities used by various components of Intel oneAPI Rendering Toolkit.
builddeps  :
    - intel-tbb-devel
rundeps    :
    - devel :
        - intel-tbb-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/bin
